name: currency_converter
description: "A Flutter currency converter app with Clean Architecture + BLoC pattern"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Networking
  dio: ^5.7.0

  # Database
  sqflite: ^2.4.1
  path: ^1.9.0

  # Image Loading
  cached_network_image: ^3.4.1

  # Charts
  fl_chart: ^0.69.2

  # Functional Programming
  dartz: ^0.10.1

  # Network Connectivity
  internet_connection_checker: ^3.0.1
  flutter_svg: ^2.2.3

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  injectable_generator: ^2.6.3
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
